/*
 * CanCon Radio — DJ engine (reference implementation, no dependencies)
 *
 * Turns a track's fact sheet (dj_facts_local.jsonl) into short spoken links
 * between songs, in English or French, and speaks them with the browser's
 * built-in voices (Web Speech API).
 *
 * THE RULE: phrasing varies, facts never do. Every clause below is built only
 * from a field that exists in the fact sheet. Missing field -> clause skipped.
 * Nothing is generated by a language model. (A neural TTS voice can replace
 * speak() later without touching the wording.)
 *
 *   const dj = CanConDJ.create({ lang: "en", duck: v => player.setVolume(v) });
 *   const line = dj.link(previousTrack, nextTrack);   // text
 *   await dj.say(line);                                // speaks, ducking music
 */
(function (root) {
  "use strict";

  const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
  const norm = (s) => (s || "").normalize("NFKD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^\w ]+/g, " ").replace(/\s+/g, " ").trim();
  const has = (t, ...keys) => keys.every((k) => t && t[k] !== undefined && t[k] !== null && t[k] !== "");

  const NUM_EN = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"];
  const NUM_FR = ["zéro", "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf", "dix"];
  const PROV_FR = {
    "Alberta": "en Alberta", "British Columbia": "en Colombie-Britannique", "Manitoba": "au Manitoba",
    "New Brunswick": "au Nouveau-Brunswick", "Newfoundland and Labrador": "à Terre-Neuve-et-Labrador",
    "Nova Scotia": "en Nouvelle-Écosse", "Ontario": "en Ontario", "Prince Edward Island": "à l'Île-du-Prince-Édouard",
    "Quebec": "au Québec", "Saskatchewan": "en Saskatchewan", "Yukon": "au Yukon",
    "the Northwest Territories": "dans les Territoires du Nord-Ouest", "Nunavut": "au Nunavut",
  };
  const PROV_DE = {
    "Alberta": "de l'Alberta", "British Columbia": "de la Colombie-Britannique", "Manitoba": "du Manitoba",
    "New Brunswick": "du Nouveau-Brunswick", "Newfoundland and Labrador": "de Terre-Neuve-et-Labrador",
    "Nova Scotia": "de la Nouvelle-Écosse", "Ontario": "de l'Ontario", "Prince Edward Island": "de l'Île-du-Prince-Édouard",
    "Quebec": "du Québec", "Saskatchewan": "de la Saskatchewan", "Yukon": "du Yukon",
    "the Northwest Territories": "des Territoires du Nord-Ouest", "Nunavut": "du Nunavut",
  };
  const AWARD_FR = { "Polaris Music Prize": "prix Polaris", "Polaris Heritage Prize": "prix Héritage Polaris",
                     "JUNO Album of the Year": "JUNO de l'album de l'année" };

  // ---------------- English ----------------
  const EN = {
    origin(t) {
      if (!has(t, "place")) return has(t, "province") ? pick([`out of ${t.province}`, `from ${t.province}`]) : "";
      const where = has(t, "province") && t.place !== t.province ? `${t.place}, ${t.province.replace(/^the /, "")}` : t.place;
      if (t.basis === "formed in") return pick([`a band formed in ${where}`, `out of ${where}`]);
      return pick([`from ${where}`, `out of ${where}`]);
    },
    album(t) {
      if (!has(t, "album") || norm(t.album) === norm(t.title)) return has(t, "year") ? `from ${t.year}` : "";
      const name = norm(t.album) === norm(t.artist) ? "the self-titled album" : `the album ${t.album}`;
      return has(t, "year") ? pick([`off ${name}, ${t.year}`, `from ${t.year}'s ${name.replace(/^the /, "")}`])
                            : `off ${name}`;
    },
    chart(t) {
      if (!has(t, "peak", "chart", "chart_year") || t.peak > 40) return "";
      const chart = t.chart === "Billboard Canadian Hot 100" ? "the Canadian Hot 100" : t.chart === "RPM" ? "the RPM chart" : `the ${t.chart}`;
      if (t.peak === 1) return pick([`a number one on ${chart} in ${t.chart_year}`, `it hit number one on ${chart} back in ${t.chart_year}`]);
      const n = t.peak <= 10 ? NUM_EN[t.peak] : t.peak;
      return pick([`it peaked at number ${n} on ${chart} in ${t.chart_year}`, `a top ${t.peak <= 10 ? "ten" : "forty"} hit on ${chart} in ${t.chart_year}`]);
    },
    award(t) {
      const a = (t.awards || []).slice().sort((x, y) => (x.result === "winner" ? -1 : 1))[0];
      if (!a) return t.juno_single === "won" ? "a JUNO-winning single" : "";
      if (a.award === "JUNO Album of the Year") return a.result === "winner" ? `from the ${a.year} JUNO Album of the Year` : `from a ${a.year} JUNO Album of the Year nominee`;
      if (a.award === "Polaris Heritage Prize") return "from a Polaris Heritage Prize classic";
      return a.result === "winner" ? `from the ${a.year} Polaris Prize-winning album` : `from a ${a.year} Polaris Prize shortlisted album`;
    },
    back(t) {
      const title = has(t, "title") ? t.title : null;
      const head = title ? pick([`That was ${title} by ${t.artist}`, `${t.artist}, with ${title}`, `You just heard ${t.artist} — ${title}`])
                         : `That was ${t.artist}`;
      const extras = [this.origin(t), this.award(t) || this.chart(t) || this.album(t)].filter(Boolean);
      return extras.length ? `${head}, ${extras.join(", ")}.` : `${head}.`;
    },
    next(t) {
      const where = has(t, "place") ? ` from ${t.place}` : has(t, "province") ? ` out of ${t.province}` : "";
      if (has(t, "title")) return pick([`Coming up: ${t.artist}${where}, with ${t.title}.`, `Next up, ${t.title} by ${t.artist}.`, `Here's ${t.artist}${where}.`]);
      return `Here's ${t.artist}${where}.`;
    },
    ids: ["You're listening to CanCon Radio — coast to coast.", "CanCon Radio. All Canadian, all the time.",
          "This is CanCon Radio — the Great Canadian Songbook.", "CanCon Radio, from sea to sea to sea."],
  };

  // ---------------- Français ----------------
  const FR = {
    de(name) { return /^[aeiouhéèêàâîôû]/i.test(name) ? `d'${name}` : `de ${name}`; },   // "de Yellowknife"
    origin(t) {
      if (!has(t, "place")) return has(t, "province") && PROV_DE[t.province] ? `originaire ${PROV_DE[t.province]}` : "";
      const tail = has(t, "province") && PROV_FR[t.province] && t.place !== t.province ? `, ${PROV_FR[t.province]}` : "";
      if (t.basis === "formed in") return `un groupe formé à ${t.place}${tail}`;   // "originaire" is gender-neutral
      return `originaire ${this.de(t.place)}${tail}`;
    },
    album(t) {
      if (!has(t, "album") || norm(t.album) === norm(t.title)) return has(t, "year") ? `paru en ${t.year}` : "";
      const name = norm(t.album) === norm(t.artist) ? "l'album homonyme" : `l'album ${t.album}`;
      return has(t, "year") ? `tiré de ${name}, ${t.year}` : `tiré de ${name}`;
    },
    chart(t) {
      if (!has(t, "peak", "chart", "chart_year") || t.peak > 40) return "";
      const chart = t.chart === "Billboard Canadian Hot 100" ? "au Canadian Hot 100" : t.chart === "RPM" ? "au palmarès RPM" : `au ${t.chart}`;
      if (t.peak === 1) return `numéro un ${chart} en ${t.chart_year}`;
      const n = t.peak <= 10 ? NUM_FR[t.peak] : t.peak;
      return `numéro ${n} ${chart} en ${t.chart_year}`;
    },
    award(t) {
      const a = (t.awards || []).slice().sort((x, y) => (x.result === "winner" ? -1 : 1))[0];
      if (!a) return t.juno_single === "won" ? "un simple primé aux JUNO" : "";
      const name = AWARD_FR[a.award] || a.award;
      if (a.award === "Polaris Heritage Prize") return "un classique du prix Héritage Polaris";
      return a.result === "winner" ? `tiré de l'album lauréat du ${name} ${a.year}` : `tiré d'un album finaliste au ${name} ${a.year}`;
    },
    back(t) {
      const title = has(t, "title") ? t.title : null;
      const head = title ? pick([`C'était ${title}, ${this.de(t.artist)}`, `${t.artist}, avec ${title}`, `Vous venez d'entendre ${t.artist} — ${title}`])
                         : `C'était ${t.artist}`;
      const extras = [this.origin(t), this.award(t) || this.chart(t) || this.album(t)].filter(Boolean);
      return extras.length ? `${head}, ${extras.join(", ")}.` : `${head}.`;
    },
    next(t) {
      const where = !has(t, "place") ? "" : t.basis === "formed in" ? `, ${this.de(t.place)}` : `, originaire ${this.de(t.place)}`;
      if (has(t, "title")) return pick([`À suivre : ${t.artist}, avec ${t.title}.`, `Maintenant, ${t.title}, ${this.de(t.artist)}.`, `Voici ${t.artist}${where}.`]);
      return `Voici ${t.artist}${where}.`;
    },
    ids: ["Vous écoutez CanCon Radio, d'un océan à l'autre.", "CanCon Radio : cent pour cent canadien.",
          "Ici CanCon Radio, le grand répertoire de la chanson canadienne."],
  };

  function create(opts = {}) {
    const state = { lang: opts.lang || "en", count: 0, idEvery: opts.idEvery || 4, duck: opts.duck || (() => {}), volume: opts.volume || 100 };
    const T = () => (state.lang === "fr" ? FR : EN);

    function link(prev, next) {
      state.count += 1;
      const parts = [];
      if (prev) parts.push(T().back(prev));
      if (state.count % state.idEvery === 0) parts.push(pick(T().ids));
      if (next) parts.push(T().next(next));
      return parts.join(" ");
    }

    function voice() {
      const vs = (root.speechSynthesis && root.speechSynthesis.getVoices()) || [];
      const want = state.lang === "fr" ? ["fr-CA", "fr"] : ["en-CA", "en-GB", "en"];
      for (const w of want) { const v = vs.find((x) => x.lang && x.lang.startsWith(w)); if (v) return v; }
      return null;
    }

    function say(text) {
      return new Promise((resolve) => {
        if (!text || !root.speechSynthesis) return resolve();
        const u = new SpeechSynthesisUtterance(text);
        const v = voice(); if (v) u.voice = v;
        u.lang = state.lang === "fr" ? "fr-CA" : "en-CA";
        u.rate = 1.02; u.pitch = 1;
        state.duck(Math.round(state.volume * 0.25));                    // music down under the voice
        let done = false;
        const finish = () => { if (done) return; done = true; state.duck(state.volume); resolve(); };
        u.onend = u.onerror = finish;
        setTimeout(finish, 2500 + text.length * 90);                    // some browsers never fire onend
        root.speechSynthesis.cancel();
        root.speechSynthesis.speak(u);
      });
    }

    return { link, say, setLang: (l) => (state.lang = l), get lang() { return state.lang; } };
  }

  root.CanConDJ = { create, _EN: EN, _FR: FR };
})(typeof window !== "undefined" ? window : globalThis);
